export const extracts = [
  {
    id: "0",
    name: "Conta 00",
    bank: "Banco do Brasil",
    value: 1002.89,
    type: "recebimento",
    type_account: "poupança",
    natureza: "Resgate",
  },
  {
    id: "1",
    name: "Conta 01",
    bank: "Bradesco",
    value: -322.89,
    type: "pagamento",
    type_account: "account corrente",
    natureza: "Transferência",
  },
  {
    id: "2",
    name: "account 03",
    bank: "Caixa Economica Federal",
    value: -124.54,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Pix",
  },
  {
    id: "3",
    name: "account 04",
    bank: "Banco Itau",
    value: -69.85,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "4",
    name: "account 04",
    bank: "Banco Itau",
    value: -69.85,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "5",
    name: "account 04",
    bank: "Banco Itau",
    value: -69.85,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "6",
    name: "account 04",
    bank: "Banco Itau",
    value: -69.85,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "7",
    name: "account 04",
    bank: "Banco Itau",
    value: -469.85,
    type: "pagamento",
    type_account: "Corrente",
    natureza: "Transferência",
  },
];
