export const extratos = [
  {
    id: "0",
    nome: "Conta 00",
    banco: "Banco do Brasil",
    valor: 1002.89,
    tipo: "recebimento",
    tipo_conta: "poupança",
    natureza: "Resgate",
  },
  {
    id: "1",
    nome: "Conta 01",
    banco: "Bradesco",
    valor: -322.89,
    tipo: "pagamento",
    tipo_conta: "conta corrente",
    natureza: "Transferência",
  },
  {
    id: "2",
    nome: "conta 03",
    banco: "Caixa Economica Federal",
    valor: -124.54,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Pix",
  },
  {
    id: "3",
    nome: "conta 04",
    banco: "Banco Itau",
    valor: -69.85,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "4",
    nome: "conta 04",
    banco: "Banco Itau",
    valor: -69.85,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "5",
    nome: "conta 04",
    banco: "Banco Itau",
    valor: -69.85,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "6",
    nome: "conta 04",
    banco: "Banco Itau",
    valor: -69.85,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Transferência",
  },
  {
    id: "7",
    nome: "conta 04",
    banco: "Banco Itau",
    valor: -469.85,
    tipo: "pagamento",
    tipo_conta: "Corrente",
    natureza: "Transferência",
  },
];
